Добавляет отправку сообщения в телегам

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -33,7 +33,7 @@ jobs:
       - name: Run flake8 and generate HTML report
         id: flake8_check
         run: |
-          flake8 . --config=setup.cfg --format=html --htmldir=flake-report || echo "flake8 failed" >> $GITHUB_ENV
+          flake8 . --config=setup.cfg --format=html --htmldir=flake-report || echo "flake8_failed=true" >> $GITHUB_ENV
 
       - name: Upload HTML report as artifact
         uses: actions/upload-artifact@v4
@@ -44,22 +44,7 @@ jobs:
       - name: Run mypy type check
         id: mypy_check
         run: |
-          mypy . || echo "mypy failed" >> $GITHUB_ENV
-
-      - name: Set exit code based on checks
-        id: set_exit_code
-        run: |
-          if [[ "${{ steps.flake8_check.outcome }}" == "failure" ]]; then
-            echo "flake8_failed=true" >> $GITHUB_ENV
-          else
-            echo "flake8_failed=false" >> $GITHUB_ENV
-          fi
-
-          if [[ "${{ steps.mypy_check.outcome }}" == "failure" ]]; then
-            echo "mypy_failed=true" >> $GITHUB_ENV
-          else
-            echo "mypy_failed=false" >> $GITHUB_ENV
-          fi
+          mypy . || echo "mypy_failed=true" >> $GITHUB_ENV
 
       - name: Send Telegram notification
         if: always()
